sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    master-host: 192.168.174.130
    slave-host: 192.168.174.131
    port: 3306
    database: sky-take-out
    username: maple
    password: *****
    type: com.alibaba.druid.pool.DruidDataSource
  alioss:
    endpoint: ***
    access-key-secret: ****
    access-key-id: *****
    bucket-name: ****
  redis:
    host: localhost
    port: 6379
    password: ****
    database: 10
  wechat:
    secret: *****
    appid: ******
    mchid: ****
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php
