sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: ssw200212
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-secret: UbXh73fwUrNXN4CIet4hBxW1pOpBgf
    access-key-id: LTAI5tHPGGCQChdiF1GpGLQ7
    bucket-name: mape-take-out
  redis:
    host: localhost
    port: 6379
    password: ssw200212
    database: 10
